;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🌍 Google服务,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/google.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/Apple.list
ruleset=🤖 Claude,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/claude.list
ruleset=🤖 OpenAI,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/openai.list
ruleset=🎸 Rockstar,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/rockstar.list
ruleset=🎮 Steam商店,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 Steam下载,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/Ruleset/SteamDownload.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🎬 Netflix,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=📱 Telegram,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/Telegram.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/Microsoft.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/MGX-LJY/ACL4SSR/master/Clash/ProxyMedia.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]DIRECT`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇲🇴 澳门节点`[]🇷🇺 俄罗斯节点`[]🇩🇪 德国节点`[]🇳🇱 荷兰节点`[]🇳🇴 挪威节点`[]🇸🇪 瑞典节点`[]🇦🇪 中东节点`[]🇨🇦 加拿大节点`[]🇪🇺 欧洲其他节点

custom_proxy_group=🚀 手动切换`select`.*

custom_proxy_group=🤖 Claude`select`[]🚀 节点选择`[]🚀 手动切换`[]🇺🇲 美国节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇲🇴 澳门节点`[]🇷🇺 俄罗斯节点`[]🇩🇪 德国节点`[]🇳🇱 荷兰节点`[]🇳🇴 挪威节点`[]🇸🇪 瑞典节点`[]🇦🇪 中东节点`[]🇨🇦 加拿大节点`[]🇪🇺 欧洲其他节点

custom_proxy_group=🤖 OpenAI`select`[]🚀 节点选择`[]🚀 手动切换`[]🇺🇲 美国节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇲🇴 澳门节点`[]🇷🇺 俄罗斯节点`[]🇩🇪 德国节点`[]🇳🇱 荷兰节点`[]🇳🇴 挪威节点`[]🇸🇪 瑞典节点`[]🇦🇪 中东节点`[]🇨🇦 加拿大节点`[]🇪🇺 欧洲其他节点

custom_proxy_group=🎸 Rockstar`select`[]🚀 节点选择`[]🚀 手动切换`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇲🇴 澳门节点`[]🇷🇺 俄罗斯节点`[]🇩🇪 德国节点`[]🇳🇱 荷兰节点`[]🇳🇴 挪威节点`[]🇸🇪 瑞典节点`[]🇦🇪 中东节点`[]🇨🇦 加拿大节点`[]🇪🇺 欧洲其他节点

custom_proxy_group=🎮 Steam商店`select`[]🚀 节点选择`[]🚀 手动切换`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇲🇴 澳门节点`[]🇷🇺 俄罗斯节点`[]🇩🇪 德国节点`[]🇳🇱 荷兰节点`[]🇳🇴 挪威节点`[]🇸🇪 瑞典节点`[]🇦🇪 中东节点`[]🇨🇦 加拿大节点`[]🇪🇺 欧洲其他节点

custom_proxy_group=🎮 Steam下载`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换

custom_proxy_group=📺 哔哩哔哩`select`[]DIRECT`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇨🇳 台湾节点`[]🚀 节点选择`[]🚀 手动切换

custom_proxy_group=🎬 Netflix`select`[]🚀 节点选择`[]🚀 手动切换`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇨🇳 台湾节点`[]🇨🇦 加拿大节点`[]🇪🇺 欧洲其他节点

custom_proxy_group=📱 Telegram`select`[]🚀 节点选择`[]🚀 手动切换`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇲🇴 澳门节点`[]🇷🇺 俄罗斯节点`[]🇩🇪 德国节点`[]🇳🇱 荷兰节点`[]🇳🇴 挪威节点`[]🇸🇪 瑞典节点`[]🇦🇪 中东节点`[]🇨🇦 加拿大节点`[]🇪🇺 欧洲其他节点

custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇲🇴 澳门节点`[]🇷🇺 俄罗斯节点`[]🇩🇪 德国节点`[]🇳🇱 荷兰节点`[]🇳🇴 挪威节点`[]🇸🇪 瑞典节点`[]🇦🇪 中东节点`[]🇨🇦 加拿大节点`[]🇪🇺 欧洲其他节点

custom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇲🇴 澳门节点`[]🇷🇺 俄罗斯节点`[]🇩🇪 德国节点`[]🇳🇱 荷兰节点`[]🇳🇴 挪威节点`[]🇸🇪 瑞典节点`[]🇦🇪 中东节点`[]🇨🇦 加拿大节点`[]🇪🇺 欧洲其他节点

custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇲🇴 澳门节点`[]🇷🇺 俄罗斯节点`[]🇩🇪 德国节点`[]🇳🇱 荷兰节点`[]🇳🇴 挪威节点`[]🇸🇪 瑞典节点`[]🇦🇪 中东节点`[]🇨🇦 加拿大节点`[]🇪🇺 欧洲其他节点

custom_proxy_group=🌍 Google服务`select`[]🚀 节点选择`[]🚀 手动切换`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇲🇴 澳门节点`[]🇷🇺 俄罗斯节点`[]🇩🇪 德国节点`[]🇳🇱 荷兰节点`[]🇳🇴 挪威节点`[]🇸🇪 瑞典节点`[]🇦🇪 中东节点`[]🇨🇦 加拿大节点`[]🇪🇺 欧洲其他节点

custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🚀 手动切换`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇲🇴 澳门节点`[]🇷🇺 俄罗斯节点`[]🇩🇪 德国节点`[]🇳🇱 荷兰节点`[]🇳🇴 挪威节点`[]🇸🇪 瑞典节点`[]🇦🇪 中东节点`[]🇨🇦 加拿大节点`[]🇪🇺 欧洲其他节点

custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换

custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT`[]🚀 手动切换

custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT`[]🚀 手动切换

custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🚀 手动切换`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇲🇴 澳门节点`[]🇷🇺 俄罗斯节点`[]🇩🇪 德国节点`[]🇳🇱 荷兰节点`[]🇳🇴 挪威节点`[]🇸🇪 瑞典节点`[]🇦🇪 中东节点`[]🇨🇦 加拿大节点`[]🇪🇺 欧洲其他节点

custom_proxy_group=🇭🇰 香港节点`select`(港|HK|Hong Kong|香港|香港节点)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇯🇵 日本节点`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇺🇲 美国节点`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇸🇬 狮城节点`select`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇰🇷 韩国节点`select`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇬🇧 英国节点`select`(英国|伦敦|Manchester|GB|UK|Britain|England|London)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇫🇷 法国节点`select`(法国|巴黎|FR|France|Paris)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇲🇴 澳门节点`select`(澳门|MO|Macao|Macau)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇷🇺 俄罗斯节点`select`(俄罗斯|RU|Russia|Moscow)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇩🇪 德国节点`select`(德国|Berlin|DE|Germany)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇳🇱 荷兰节点`select`(荷兰|NL|Netherlands|Amsterdam)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇳🇴 挪威节点`select`(挪威|NO|Norway|Oslo)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇸🇪 瑞典节点`select`(瑞典|SE|Sweden|Stockholm)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇦🇪 中东节点`select`(中东|阿联酋|Dubai|UAE|Middle East|阿根廷|阿|土耳其|土|中东|以色列|Israel|约旦|Jordan|伊朗|Iran|巴林|Bahrain|卡塔尔|Qatar|乔治亚|Georgia|巴基斯坦|Pakistan|哈萨克斯坦|Kazakhstan|乌兹别克斯坦|Uzbekistan|叙利亚)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇨🇦 加拿大节点`select`(加拿大|温哥华|多伦多|CA|Canada|Vancouver|Toronto)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇪🇺 欧洲其他节点`select`(法兰克福|Frankfurt|瑞士|Switzerland|丹麦|Denmark|芬兰|Finland|冰岛|Iceland|捷克|Czech Republic|希腊|Greece|波兰|Poland|乌克兰|Ukraine|匈牙利|Hungary|卢森堡|Luxembourg|奥地利|Austria|意大利|Italy|比利时|Belgium|爱尔兰|Ireland|立陶宛|Lithuania|西班牙|Spain|葡萄牙|Portugal|安道尔|Andorra|马耳他|Malta|克罗地亚|Croatia|北马其颜|North Macedonia|塞尔维亚|Serbia|塞浦路斯|Cyprus|拉脱维亚|Latvia|摩尔多瓦|Moldova|斯洛伐克|Slovakia|爱沙尼亚|Estonia|罗马尼亚|Romania|斯洛文尼亚|Slovenia|波斯尼亚和黑塞哥维那|Bosnia and Herzegovina|法属留尼汪|Reunion)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇨🇳 台湾节点`select`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50

;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
;luck
